name: bloodbook
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth:
  cloud_firestore:
  geoflutterfire:
  firebase_core:
  firebase_messaging:
  firebase_storage:
  image_picker:
  flexible: ^0.1.4
  geolocator: ^6.0.0+4
  http: ^0.12.2
  geocoding: ^1.0.2
  location: ^3.0.0
  flutter_spinkit: ^4.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
  uses-material-design: true